create table if not exists public.anonymous_channels (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.anonymous_channel_memberships (
  channel_id uuid not null references public.anonymous_channels(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (channel_id, user_id)
);

create table if not exists public.anonymous_posts (
  id uuid primary key default gen_random_uuid(),
  channel_id uuid not null references public.anonymous_channels(id) on delete restrict,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  tags text[] not null default '{}',
  deleted_at timestamptz,
  moderation_status text not null default 'visible' check (moderation_status in ('visible','hidden','removed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.anonymous_post_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.anonymous_posts(id) on delete cascade,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  deleted_at timestamptz,
  moderation_status text not null default 'visible' check (moderation_status in ('visible','hidden','removed')),
  created_at timestamptz not null default now()
);

create table if not exists public.anonymous_post_votes (
  post_id uuid not null references public.anonymous_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  vote smallint not null check (vote in (-1, 1)),
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.anonymous_reports (
  id uuid primary key default gen_random_uuid(),
  post_id uuid references public.anonymous_posts(id) on delete cascade,
  comment_id uuid references public.anonymous_post_comments(id) on delete cascade,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reason text not null,
  created_at timestamptz not null default now(),
  check ((post_id is not null) <> (comment_id is not null))
);

create unique index if not exists anonymous_reports_post_once
  on public.anonymous_reports(post_id, reporter_id)
  where post_id is not null;

create unique index if not exists anonymous_reports_comment_once
  on public.anonymous_reports(comment_id, reporter_id)
  where comment_id is not null;

create table if not exists public.nearby_people_preferences (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  enabled boolean not null default false,
  approximate_lat numeric(8,4),
  approximate_lng numeric(8,4),
  radius_km numeric(5,1) not null default 5,
  interests text[] not null default '{}',
  last_updated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (approximate_lat between -90 and 90),
  check (approximate_lng between -180 and 180)
);

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text not null,
  category text not null default 'General',
  priority text not null default 'medium' check (priority in ('low','medium','high','critical')),
  status text not null default 'new' check (status in ('new','in_progress','waiting_for_user','resolved','closed')),
  module text not null default 'Social 24x7',
  platform text,
  screenshot_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.support_ticket_responses (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  responder_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  is_staff boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.support_feature_requests (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text not null,
  category text not null default 'General',
  status text not null default 'under_review' check (status in ('under_review','planned','in_progress','released','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.support_feature_votes (
  feature_id uuid not null references public.support_feature_requests(id) on delete cascade,
  voter_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (feature_id, voter_id)
);

create table if not exists public.support_faqs (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  answer text not null,
  category text not null default 'General',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.support_faq_feedback (
  faq_id uuid not null references public.support_faqs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  helpful boolean not null,
  created_at timestamptz not null default now(),
  primary key (faq_id, user_id)
);

alter table public.missing_person_reports
  add column if not exists urgent boolean not null default false,
  add column if not exists reward_minor bigint not null default 0,
  add column if not exists reward_terms text not null default '',
  add column if not exists archived_at timestamptz;

insert into public.anonymous_channels (slug, name, description)
values
  ('general', 'General Discussion', 'Share your thoughts and opinions'),
  ('technology', 'Technology', 'Discuss latest tech trends'),
  ('lifestyle', 'Lifestyle', 'Life tips and experiences'),
  ('confessions', 'Anonymous Confessions', 'Reflect without exposing your public profile')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description;

insert into public.support_faqs (question, answer, category, sort_order)
values
  ('How do I reset my payment method?', 'Go to the payment screen in the relevant module and choose Add New Method or Manage Payment Methods when payment support is enabled.', 'Payments', 10),
  ('Why am I not receiving notifications?', 'Check device notification permissions and your Social 24x7 account notification preferences.', 'Account', 20),
  ('How do I report unsafe behaviour?', 'Use the report action inside the relevant feature. Emergency situations should be reported to local authorities first.', 'Safety', 30)
on conflict do nothing;

alter table public.anonymous_channels enable row level security;
alter table public.anonymous_channel_memberships enable row level security;
alter table public.anonymous_posts enable row level security;
alter table public.anonymous_post_comments enable row level security;
alter table public.anonymous_post_votes enable row level security;
alter table public.anonymous_reports enable row level security;
alter table public.nearby_people_preferences enable row level security;
alter table public.support_tickets enable row level security;
alter table public.support_ticket_responses enable row level security;
alter table public.support_feature_requests enable row level security;
alter table public.support_feature_votes enable row level security;
alter table public.support_faqs enable row level security;
alter table public.support_faq_feedback enable row level security;

drop policy if exists "anonymous channels read" on public.anonymous_channels;
create policy "anonymous channels read" on public.anonymous_channels for select to authenticated using (true);

drop policy if exists "anonymous memberships read" on public.anonymous_channel_memberships;
create policy "anonymous memberships read" on public.anonymous_channel_memberships for select to authenticated using (true);

drop policy if exists "anonymous membership own insert" on public.anonymous_channel_memberships;
create policy "anonymous membership own insert" on public.anonymous_channel_memberships for insert to authenticated with check (user_id = (select auth.uid()));

drop policy if exists "anonymous membership own delete" on public.anonymous_channel_memberships;
create policy "anonymous membership own delete" on public.anonymous_channel_memberships for delete to authenticated using (user_id = (select auth.uid()));

drop policy if exists "anonymous posts visible read" on public.anonymous_posts;
create policy "anonymous posts visible read" on public.anonymous_posts for select to authenticated
using (deleted_at is null and moderation_status = 'visible');

drop policy if exists "anonymous posts owner insert" on public.anonymous_posts;
create policy "anonymous posts owner insert" on public.anonymous_posts for insert to authenticated with check (owner_id = (select auth.uid()));

drop policy if exists "anonymous posts owner update" on public.anonymous_posts;
create policy "anonymous posts owner update" on public.anonymous_posts for update to authenticated
using (owner_id = (select auth.uid()))
with check (owner_id = (select auth.uid()));

drop policy if exists "anonymous comments visible read" on public.anonymous_post_comments;
create policy "anonymous comments visible read" on public.anonymous_post_comments for select to authenticated
using (deleted_at is null and moderation_status = 'visible');

drop policy if exists "anonymous comments owner insert" on public.anonymous_post_comments;
create policy "anonymous comments owner insert" on public.anonymous_post_comments for insert to authenticated with check (owner_id = (select auth.uid()));

drop policy if exists "anonymous comments owner update" on public.anonymous_post_comments;
create policy "anonymous comments owner update" on public.anonymous_post_comments for update to authenticated
using (owner_id = (select auth.uid()))
with check (owner_id = (select auth.uid()));

drop policy if exists "anonymous votes read" on public.anonymous_post_votes;
create policy "anonymous votes read" on public.anonymous_post_votes for select to authenticated using (true);

drop policy if exists "anonymous votes own upsert" on public.anonymous_post_votes;
create policy "anonymous votes own upsert" on public.anonymous_post_votes for insert to authenticated with check (user_id = (select auth.uid()));

drop policy if exists "anonymous votes own update" on public.anonymous_post_votes;
create policy "anonymous votes own update" on public.anonymous_post_votes for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

drop policy if exists "anonymous votes own delete" on public.anonymous_post_votes;
create policy "anonymous votes own delete" on public.anonymous_post_votes for delete to authenticated using (user_id = (select auth.uid()));

drop policy if exists "anonymous reports own insert" on public.anonymous_reports;
create policy "anonymous reports own insert" on public.anonymous_reports for insert to authenticated with check (reporter_id = (select auth.uid()));

drop policy if exists "anonymous reports own read" on public.anonymous_reports;
create policy "anonymous reports own read" on public.anonymous_reports for select to authenticated using (reporter_id = (select auth.uid()));

drop policy if exists "nearby pref own read" on public.nearby_people_preferences;
create policy "nearby pref own read" on public.nearby_people_preferences for select to authenticated
using (user_id = (select auth.uid()) or enabled);

drop policy if exists "nearby pref own insert" on public.nearby_people_preferences;
create policy "nearby pref own insert" on public.nearby_people_preferences for insert to authenticated with check (user_id = (select auth.uid()));

drop policy if exists "nearby pref own update" on public.nearby_people_preferences;
create policy "nearby pref own update" on public.nearby_people_preferences for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

drop policy if exists "support tickets owner read" on public.support_tickets;
create policy "support tickets owner read" on public.support_tickets for select to authenticated using (requester_id = (select auth.uid()));

drop policy if exists "support tickets owner insert" on public.support_tickets;
create policy "support tickets owner insert" on public.support_tickets for insert to authenticated with check (requester_id = (select auth.uid()));

drop policy if exists "support tickets owner close" on public.support_tickets;
create policy "support tickets owner close" on public.support_tickets for update to authenticated
using (requester_id = (select auth.uid()))
with check (requester_id = (select auth.uid()) and status in ('new','closed'));

drop policy if exists "support responses ticket owner read" on public.support_ticket_responses;
create policy "support responses ticket owner read" on public.support_ticket_responses for select to authenticated
using (exists (select 1 from public.support_tickets t where t.id = ticket_id and t.requester_id = (select auth.uid())));

drop policy if exists "support responses requester insert" on public.support_ticket_responses;
create policy "support responses requester insert" on public.support_ticket_responses for insert to authenticated
with check (
  responder_id = (select auth.uid())
  and is_staff = false
  and exists (select 1 from public.support_tickets t where t.id = ticket_id and t.requester_id = (select auth.uid()))
);

drop policy if exists "feature requests read" on public.support_feature_requests;
create policy "feature requests read" on public.support_feature_requests for select to authenticated using (true);

drop policy if exists "feature requests owner insert" on public.support_feature_requests;
create policy "feature requests owner insert" on public.support_feature_requests for insert to authenticated with check (requester_id = (select auth.uid()));

drop policy if exists "feature requests owner update" on public.support_feature_requests;
create policy "feature requests owner update" on public.support_feature_requests for update to authenticated
using (requester_id = (select auth.uid()))
with check (requester_id = (select auth.uid()) and status = 'under_review');

drop policy if exists "feature votes read" on public.support_feature_votes;
create policy "feature votes read" on public.support_feature_votes for select to authenticated using (true);

drop policy if exists "feature votes own insert" on public.support_feature_votes;
create policy "feature votes own insert" on public.support_feature_votes for insert to authenticated with check (voter_id = (select auth.uid()));

drop policy if exists "feature votes own delete" on public.support_feature_votes;
create policy "feature votes own delete" on public.support_feature_votes for delete to authenticated using (voter_id = (select auth.uid()));

drop policy if exists "faqs read" on public.support_faqs;
create policy "faqs read" on public.support_faqs for select to authenticated using (true);

drop policy if exists "faq feedback read" on public.support_faq_feedback;
create policy "faq feedback read" on public.support_faq_feedback for select to authenticated using (true);

drop policy if exists "faq feedback own insert" on public.support_faq_feedback;
create policy "faq feedback own insert" on public.support_faq_feedback for insert to authenticated with check (user_id = (select auth.uid()));

drop policy if exists "faq feedback own update" on public.support_faq_feedback;
create policy "faq feedback own update" on public.support_faq_feedback for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('missing-person-photos', 'missing-person-photos', true, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "missing photos public read" on storage.objects;
create policy "missing photos public read" on storage.objects for select to public
using (bucket_id = 'missing-person-photos');

drop policy if exists "missing photos owner insert" on storage.objects;
create policy "missing photos owner insert" on storage.objects for insert to authenticated
with check (bucket_id = 'missing-person-photos' and owner = (select auth.uid()));

drop policy if exists "missing photos owner update" on storage.objects;
create policy "missing photos owner update" on storage.objects for update to authenticated
using (bucket_id = 'missing-person-photos' and owner = (select auth.uid()))
with check (bucket_id = 'missing-person-photos' and owner = (select auth.uid()));

grant select on public.anonymous_channels to authenticated;
grant select, insert, delete on public.anonymous_channel_memberships to authenticated;
grant select(id, channel_id, body, tags, deleted_at, moderation_status, created_at, updated_at) on public.anonymous_posts to authenticated;
grant insert(channel_id, owner_id, body, tags) on public.anonymous_posts to authenticated;
grant update(body, tags, deleted_at, updated_at) on public.anonymous_posts to authenticated;
grant select(id, post_id, body, deleted_at, moderation_status, created_at) on public.anonymous_post_comments to authenticated;
grant insert(post_id, owner_id, body) on public.anonymous_post_comments to authenticated;
grant update(body, deleted_at) on public.anonymous_post_comments to authenticated;
grant select, insert, update, delete on public.anonymous_post_votes to authenticated;
grant select, insert on public.anonymous_reports to authenticated;
grant select, insert, update on public.nearby_people_preferences to authenticated;
grant select, insert, update on public.support_tickets to authenticated;
grant select, insert on public.support_ticket_responses to authenticated;
grant select, insert, update on public.support_feature_requests to authenticated;
grant select, insert, delete on public.support_feature_votes to authenticated;
grant select on public.support_faqs to authenticated;
grant select, insert, update on public.support_faq_feedback to authenticated;

revoke select on public.missing_person_reports from authenticated;
grant select (
  id,
  reporter_id,
  person_name,
  age_text,
  photo_url,
  last_seen_city,
  last_seen_location,
  last_seen_date,
  description,
  status,
  consent_confirmed,
  urgent,
  reward_minor,
  reward_terms,
  archived_at,
  created_at,
  updated_at
) on public.missing_person_reports to authenticated;
grant insert (
  reporter_id,
  person_name,
  age_text,
  photo_url,
  last_seen_city,
  last_seen_location,
  last_seen_date,
  description,
  reporter_contact,
  status,
  consent_confirmed,
  urgent,
  reward_minor,
  reward_terms
) on public.missing_person_reports to authenticated;
grant update (
  person_name,
  age_text,
  photo_url,
  last_seen_city,
  last_seen_location,
  last_seen_date,
  description,
  reporter_contact,
  status,
  consent_confirmed,
  urgent,
  reward_minor,
  reward_terms,
  archived_at,
  updated_at
) on public.missing_person_reports to authenticated;
